### ISSUE TITLE
"You need to use Hyper.app to run this command"

### ISSUE THREAD

**Issue by stereokai** [timolins/hyperlayout#12]
When I type `hyperlayout` all I'm getting is this line: "You need to use Hyper.app to run this command"

**Comment by timolins** [comment]
Are you using Hyper.app 1.0?

**Comment by stereokai** [comment]
Indeed

**Comment by timolins** [comment]
Is 'TERM_PROGRAM' set in your environment? (Hyper should do this automatically)

**Comment by stereokai** [comment]
Doesn't look like it is...

**Comment by stereokai** [comment]
@timolins I set TERM_PROGRAM to Hyper as it's supposed to be. Now what I'm getting back is just the layout config json as in #8

**Comment by timolins** [comment]
Is hyperlayout installed in Hyper.app? `hpm install hyperlayout`

**Comment by stereokai** [comment]
Yes. It's both in `hyper.js` and installed globally via `npm install -g` as well as in the `.hyper_plugins` directory.
