### ISSUE TITLE
Open a tab or pane without running a command

### ISSUE THREAD

**Issue by SethGunnells** [timolins/hyperlayout#13]
It's not a vital request and there may already be a way to do this. Currently, I just have an empty string for a pane that I want to have as empty. A way to truly just open a new section without doing anything at all would be handy though.

**Comment by timolins** [comment]
I'm currently using `""` myself. Do you have any API suggestions?

**Comment by SethGunnells** [comment]
I was just peeking through the code to see if I could find where this makes the most sense to execute. My thoughts as of this morning are that perhaps there could be a solitary special case to simply not run a command for a pane that is specified with a `""`. Since that is effectively what is already happening, it would add just an extra bit of niceness to see that solitary prompt in the new pane.

What do you think?

**Comment by timolins** [comment]
Yeah, I was thinking the same. Shouldn't be hard to execute. I will implement this in the next release.

**Comment by SethGunnells** [comment]
Awesome! If I can help, let me know. I'm happy to PR.
