### ISSUE TITLE
Multiple tabs - only firing code in first tab

### ISSUE THREAD

**Issue by sp90** [timolins/hyperlayout#15]
Okay so i love this package i just have this one error:

My setup:

```json
"hyperlayout": {
	"default": [
		"npm start",
		"cd ./frontend/src && gulp",
		"git status"
	]
}
```

It only runs the first command `npm start`

If i then remove the first so it looks like this:

```json
"hyperlayout": {
	"default": [
		"cd ./frontend/src && gulp",
		"git status"
	]
}
```

it still only runs the first command `cd ./frontend/src && gulp`

**Comment by alin23** [comment]
I get the same behaviour on Hyper 1.0.0

**Comment by stereokai** [comment]
@timolins are the commands supposed to be invoked automatically? Or are you supposed to press Enter manually?

**Comment by timolins** [comment]
They should invoke automatically. Hyperlayout is basically appending `\n` to each command to fire it.

**Comment by stereokai** [comment]
Oh, so there's another bug. They don't invoke automatically for me

**Comment by sp90** [comment]
I use OSX as a notice, on Hyper 1.0.0

**Comment by jschloer** [comment]
I'm also on OS X. Stepping through the code I noticed that with my generated queue it never got to the point of running the cmd action for the second pane. Basically the queue stopped processing after the split. Want  to try to look at it some more today, but it seemed like the problem was that nothing was processed after https://github.com/timolins/hyperlayout/blob/master/index.js#L93, it just exited all the way back up the work stack. Like I said I'll try to take another look later to see if it's more of a work() problem, or more how the queue is being generated. I don't fully understand how that works just yet.

**Comment by timolins** [comment]
Okay, for some reason a duplicate `work()` call sneaked into the code. Issue seems to be resolved for me know inside master. Can someone else confirm this? @jschloer

**Comment by sp90** [comment]
@timolins if this is true, it calls for a hotfix :D

**Comment by alin23** [comment]
I confirm this fixed the issue. 👍
I'm using Hyper 1.0.0 on macOS.

**Comment by timolins** [comment]
Here goes `hyperlayout` 0.2.1! 🎉

@sp90

**Comment by jschloer** [comment]
Just got a chance to check and 0.2.1 looks good on my system(macOS)

**Comment by sp90** [comment]
Im challenged with updating it, im using `hpm`

**Comment by timolins** [comment]
@sp90 ⇧⌘U should do the trick.

**Comment by sp90** [comment]
Inside hyper @timolins ?

**Comment by timolins** [comment]
0.2.1 has been out for a few days now. Did it fix this issue for everyone? (Only was able to test it under macOS)

**Comment by jschloer** [comment]
Seems to be working for me, two tabs, with two sessions and working commands in all of them.

On Dec 27, 2016, at 10:51 AM, Timo <notifications@github.com<mailto:notifications@github.com>> wrote:


0.2.1 has been out for a few days now. Did it fix this issue for everyone? (Only was able to test it under macOS)

**Comment by timolins** [comment]
You are on macOS, too, I guess? Let's wait for both a Windows & a Linux user to confirm this, before closing this issue.

**Comment by timolins** [comment]
Seems to be fixed - closed.

**Comment by sp90** [comment]
👍 💯
