### ISSUE TITLE
Apply on startup

### ISSUE THREAD

**Issue by fgilio** [timolins/hyperlayout#20]
Is there a way to configure hyperlayout to apply the default global layout on startup?

**Comment by timolins** [comment]
No, that's not possible at the moment. I don't really think this should be implemented into the core, since this isn't really specific for hyperlayout. It would make more sense to build another Hyper plugin, which executes commands on start-up. This approach would also work well with hyperlayout.

**Comment by fgilio** [comment]
Yes, I agree 👍

**Comment by reckter** [comment]
This might be interesting for you: https://www.npmjs.com/package/hyper-startup :)

**Comment by fgilio** [comment]
Thanks!
