### ISSUE TITLE
How to automatically run hyperlayout?

### ISSUE THREAD

**Issue by Fedeorlandau** [timolins/hyperlayout#27]
How to automatically run hyperlayout?

I've set up my hyperlayout on ~/.hyperlayout and i would like to run it every time i open hyper

Thanks!

**Comment by timolins** [comment]
Have a look at [`hyper-startup`](https://www.npmjs.com/package/hyper-startup)! Should work perfectly with hyperlayout.

**Comment by Fedeorlandau** [comment]
[hyper-startup](https://www.npmjs.com/package/hyper-run) did the magic.

Thanks @timolins

**Comment by timolins** [comment]
😃
