### ISSUE TITLE
Trailing comma will cause invalid layout

### ISSUE THREAD

**Issue by ianfhunter** [timolins/hyperlayout#29]
Example:
```
{
  "default": {
    "entry": "vertical",
    "layout": ["echo Hello", "echo World",]
  },
  "otherlayout": ["echo Hyper", "echo Term"]
}
```
If I have left a trailing , in my layout - which i generally do out of habit with json, in case i need to go back and append fields - i don't have to worry about errors of missing commas.

If i include it in layout, it invalidates the layout and hyperlayout won't set up my layout.

It's a minor issue, but I imagine that other people are affected by it too.

**Comment by philoserf** [comment]
This is expected. The format of the configuration file is JSON. This example does not validate as JSON.

**Comment by philoserf** [comment]
for the record: the problem in the example's JSON format is the comma after "echo World".

**Comment by timolins** [comment]
Thanks for pointing that out, @philoserf!
