### ISSUE TITLE
Add GIF to README

### ISSUE THREAD

**Issue by timolins** [timolins/hyperlayout#6]
Add GIF to the header of the README to explain hyperlayout.

**Comment by timolins** [comment]
Closed in 78bc0522e6d0765bf3446d7cf4e27b16c74ad26f

**Comment by danielkalen** [comment]
Hey, what did you use to create this GIF?

**Comment by timolins** [comment]
I used **[kap](https://github.com/wulkano/kap)** to record my **[Hyper](hyper.is)** terminal. _(both of them are awesome)_

The background was masked out in Photoshop.
