### ISSUE TITLE
Can't find/call hyperlayout directly from command line (missing exec symlink)

### ISSUE THREAD

**Issue by kevingelion** [timolins/hyperlayout#9]
Version 0.8.3
macOS Sierra

I currently can't call hyperlayout directly from the command line - for some reason it isn't recognized as an alias or there's no symlink somewhere but I'm forced to call it from within `node_modules` inside `hyper_plugins` manually.

**Comment by timolins** [comment]
You mean `hyperlayout`, right? ;)

Are you sure you have it installed in Hyper AND as global NPM module?

**Comment by kevingelion** [comment]
Sorry about the typo! Didn't notice in the README that i needed to install `hyperlayout` as a global npm module as well as `hpm-cli`. Thanks!
